### ISSUE TITLE
Audio issues in Futari wa Precure - Ariennai! Yume no Sono wa Daimeikyuu

### ISSUE THREAD

**Issue by fleroviux** [nba-emu/NanoBoyAdvance#325]
See https://github.com/skylersaleh/SkyEmu/issues/291#issuecomment-1696445654. Allegedly NBAs behavior is inconsistent.

**Comment by Kirby0Louise** [comment]
Hi, thanks for taking interest in the bug I found.  I've attached some save states to help reproduce the bug.  State 1 is for the title screen, simply wait until the title shout finishes and the PSG channels are active, then press start.  State 2 is for the end of level sfx bug, simply press right to complete the level

[Futari wa Pretty Cure - Arienaai! Yume no Sono wa Daimeikyuu (Japan).zip](https://github.com/nba-emu/NanoBoyAdvance/files/12480485/Futari.wa.Pretty.Cure.-.Arienaai.Yume.no.Sono.wa.Daimeikyuu.Japan.zip)

Let me know if any more help is needed!

**Comment by fleroviux** [comment]
Thanks for this! Could you quickly tell me what version of NanoBoyAdvance you used to create the savestates? Thanks.

**Comment by Kirby0Louise** [comment]
1.7.1 from the releases tab.

**Comment by Kirby0Louise** [comment]
Is there any way to freeze a register to a desired value?  I am investigating the bug further and this could help.  No worries if it's not possible.

**Comment by fleroviux** [comment]
Sorry, at the moment this is not possible!

**Comment by fleroviux** [comment]
Could you retest the game with the latest [development build](https://nightly.link/nba-emu/NanoBoyAdvance/workflows/build/master) please? I just pushed some fixes to the envelope volume calculations which might affect this game.

**Comment by Kirby0Louise** [comment]
Sorry for the late response, just saw your post.  Unfortunately this did not fix the issue.
